Fix nanosecond timestamps on high sierra
codekitchen/fsevents_to_vm pull request #9
Opened 2018-05-23 19:28 UTC by ms-ati

On Mac OS High Sierra, the new file system (APFS) has changed file timestamps
from second to nanosecond resolution. This has broken many dinghy-based
development environments, please see
https://github.com/codekitchen/dinghy/issues/269 for more details.

To become compatible with nanosecond timestamps, this patch does the following:

  1. Format times as ISO8601 with nanosecond resolution
  2. Via SSH invoke touch with '-d' option, which accepts ISO8601 format
  3. At startup install the GNU version of touch into Dinghy's VM

The last point is necessary because the default BusyBox touch is not
itself compatible with nanosecond timestamps in the '-d' option. We
copy the actual binary from the docker image for Ubuntu:16.04, which
is verified compatible.

Please note that, completely separately, fixes were also needed in UNFS3.

2018-05-23 19:29 UTC, ms-ati commented
When running with `--debug` for the first time:

```
bundle exec ruby exe/fsevents_to_vm start --debug --ssh-identity-file ~/.docker/machine/machines/dinghy/id_rsa --ssh-ip $(dinghy ip) ~
Checking if GNU touch already installed in Dinghy VM...
+ dinghy ssh gtouch --version
++ sh: gtouch: not found
++ exit status 127
Not installed.
Installing GNU touch from Ubuntu into Dinghy VM...
+ HOST_NFS_DIR=/Users/msiegel
++ mktemp -d /Users/msiegel/tmp/dinghy_tmp.XXXXXXXX
+ HOST_TMP_DIR=/Users/msiegel/tmp/dinghy_tmp.TAyMGFjH
+ mkdir -pv /Users/msiegel/tmp/dinghy_tmp.TAyMGFjH
+ docker run -v /Users/msiegel/tmp/dinghy_tmp.TAyMGFjH:/host_tmp_dir ubuntu:16.04 /bin/cp /usr/bin/touch /host_tmp_dir/
+ dinghy ssh sudo cp /Users/msiegel/tmp/dinghy_tmp.TAyMGFjH/touch /bin/gtouch
+ rm /Users/msiegel/tmp/dinghy_tmp.TAyMGFjH/touch
+ rmdir /Users/msiegel/tmp/dinghy_tmp.TAyMGFjH
+ dinghy ssh gtouch --version
+ grep 'GNU coreutils'
touch (GNU coreutils) 8.25
done.
Watching /Users/msiegel and forwarding events to Dinghy VM...
```

2018-05-23 19:30 UTC, ms-ati commented
And then when running with `--debug` a second time:

```
$ bundle exec ruby exe/fsevents_to_vm start --debug --ssh-identity-file ~/.docker/machine/machines/dinghy/id_rsa --ssh-ip $(dinghy ip) ~
Checking if GNU touch already installed in Dinghy VM...
+ dinghy ssh gtouch --version
++ touch (GNU coreutils) 8.25
++ Copyright (C) 2016 Free Software Foundation, Inc.
++ License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
++ This is free software: you are free to change and redistribute it.
++ There is NO WARRANTY, to the extent permitted by law.
++
++ Written by Paul Rubin, Arnold Robbins, Jim Kingdon,
++ David MacKenzie, and Randy Smith.
Already installed.
Watching /Users/msiegel and forwarding events to Dinghy VM...
```

2018-05-27 21:23 UTC, codekitchen requested changes
Thanks for doing this. The idea looks good, I do like the simplicity of it over the other solution. We'll need to change the details of the implementation, there are people using `fsevents_to_vm` outside of Dinghy so we've been careful to avoid adding any circular dependencies on Dinghy in this code like this shelling out to `dinghy ssh`.

Rather than calling `dinghy ssh`, it's probably best to establish an SSH connection using Net::SSH the same way that the code in `ssh_emit.rb` does, possibly extracting that out into shared SSH connection code.

2018-05-27 21:23 UTC, codekitchen commented on exe/dinghy_install_gnu_touch.sh
> +HOST_NFS_DIR="${DINGHY_HOST_MOUNT_DIR:-${HOME}}"
This could be more straightforward by using the `docker cp` command, something like:


```bash
containerid=$(docker create ubuntu:16.04)
sudo docker cp $containerid:/bin/touch /bin/gtouch
docker rm $containerid
```

2018-05-27 21:23 UTC, codekitchen commented on exe/dinghy_install_gnu_touch.sh
> +docker run -v ${HOST_TMP_DIR}:/host_tmp_dir ubuntu:16.04 \
In fact, as a small optimization I think it probably makes sense to use the `codekitchen/dinghy-http-proxy` image here rather than `ubuntu:16.04`, since in the common case dinghy will have already downloaded that image. The proxy image has "touch (GNU coreutils) 8.26" at `/bin/touch`.

2018-05-27 21:23 UTC, codekitchen commented on lib/fsevents_to_vm/dinghy_install_gnu_touch.rb
> +    CHECK_COMMAND = 'dinghy ssh gtouch --version'
This check will need to use Net::SSH as well

2018-05-29 14:39 UTC, ms-ati commented
Hi @codekitchen, first of all, *thank you* for your input!

I am willing to commit to re-implementing this in terms of the `Net::SSH`. Totally happy to test out the idea that the `/bin/touch` from the `dinghy-http-proxy` might work, but since nanoseconds are not working inside that container, I had made the assumption (perhaps incorrectly) that the `touch` binary was compiled without nanoseconds support.

Totally agree that, if that `touch` binary is compatible with the host BusyBox and compiled with nanoseconds support, than it is definitely a better choice.

2018-05-29 16:30 UTC, codekitchen commented
Cool sounds good thanks. BTW I'm not sure what you mean by "since nanoseconds are not working inside that container", we don't ever call `touch` inside the `dinghy-http-proxy` container, just on the host VM (boot2docker/busybox).

2018-05-29 16:51 UTC, ms-ati commented
> BTW I'm not sure what you mean by "since nanoseconds are not working inside that container"

Thanks I may have skipped an import point there. I evaluated `dinghy-http-proxy` container as a target for executing the `touch` command there, since it will be running, rather than on the host VM, but couldn't get that to work.

2018-05-29 23:08 UTC, codekitchen commented
> Thanks I may have skipped an import point there. I evaluated dinghy-http-proxy container as a target for executing the touch command there, since it will be running, rather than on the host VM, but couldn't get that to work.

Ah, that makes a lot more sense then, OK.

2018-05-30 13:45 UTC, ms-ati commented on exe/dinghy_install_gnu_touch.sh
> +HOST_NFS_DIR="${DINGHY_HOST_MOUNT_DIR:-${HOME}}"
@codekitchen Please note that `docker cp` mode of operation is to _"Copy files/folders between a container and the local filesystem"_.

This means that we still need the local temp file on the host, do we not?

2018-05-30 22:01 UTC, codekitchen commented
Hm I don't think I was clear enough, sorry. What I mean is that if you SSH into the VM and run those `sudo docker cp` steps there, that'll copy the binary directly from the container into `/bin/touch` on the VM. So you can skip all the steps to create a temporary directory under the NFS mount and all of that.

2018-05-31 01:33 UTC, ms-ati commented
Great idea! I'll try that.

2018-06-04 19:41 UTC, ms-ati commented
@codekitchen Ok! This PR has been updated to remove any explicit dependency on Dinghy. It now works exactly as discussed above. Looking forward to your re-review :)

2018-06-05 18:09 UTC, codekitchen approved these changes

2018-06-05 18:09 UTC, merged

2018-06-05 18:09 UTC, codekitchen commented
Sweet, looks good and everything seems to be working great when I pull it down locally. Thanks for doing all that. I'll cut a new release of Dinghy today or tomorrow.

2018-06-05 19:44 UTC, ms-ati commented
Nice! @codekitchen could I impose on you to do the following additional steps:

1. Release new Dinghy that depends on this fsevents_to_vm
2. Update homebrew-dinghy to require the new Dinghy
3. Add a highly visible note to the README to inform people that it now supports nanosecond timestamps on High Sierra, and please run `brew update; brew upgrade dinghy` to fix it
4. Close https://github.com/codekitchen/dinghy/issues/269 with an informative message outlining the final state (for future folks reading it)?

2018-06-06 00:35 UTC, codekitchen commented
Yes, updating homebrew-dinghy is part of releasing a new Dinghy version. Thanks. It'll be in the CHANGELOG.